const v=document.getElementById('v'),a=document.getElementById('a'),play=document.getElementById('play'),big=document.getElementById('big'),bar=document.getElementById('bar'),fill=document.getElementById('fill'),now=document.getElementById('now'),dur=document.getElementById('dur'),mute=document.getElementById('mute'),fs=document.getElementById('fs');
const fmt=t=>{t=Math.max(0,Math.floor(t||0));return Math.floor(t/60)+':'+String(t%60).padStart(2,'0')};
function sync(){now.textContent=fmt(a.currentTime);dur.textContent=fmt(a.duration);if(a.duration)fill.style.width=a.currentTime/a.duration*100+'%';}
function state(on){play.textContent=on?'Ⅱ':'▶';big.textContent=on?'Ⅱ':'▶';big.style.opacity=on?0:1;big.style.pointerEvents=on?'none':'auto'}
async function start(){try{if(a.paused){await a.play();v.currentTime=a.currentTime;await v.play();state(true)}else{a.pause();v.pause();state(false)}}catch(e){console.error(e);alert('O navegador não conseguiu iniciar o áudio. Clique novamente no play.')}}
play.onclick=start;big.onclick=start;v.onclick=()=>{if(a.paused)start();else start()};a.addEventListener('timeupdate',sync);a.addEventListener('loadedmetadata',sync);a.addEventListener('pause',()=>{v.pause();state(false)});a.addEventListener('play',()=>{v.play().catch(()=>{});state(true)});a.addEventListener('ended',()=>{v.pause();state(false);sync()});
setInterval(()=>{if(!a.paused&&!v.paused&&Math.abs(v.currentTime-a.currentTime)>.08)v.currentTime=a.currentTime},500);
bar.onclick=e=>{if(!a.duration)return;const r=bar.getBoundingClientRect();const t=((e.clientX-r.left)/r.width)*a.duration;a.currentTime=t;v.currentTime=t;sync()};
mute.onclick=()=>{a.muted=!a.muted;mute.textContent=a.muted?'×♫':'♫'};fs.onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.querySelector('.card').requestFullscreen?.()};
document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();start()}if(e.code==='ArrowRight'){a.currentTime=Math.min(a.duration||0,a.currentTime+5);v.currentTime=a.currentTime}if(e.code==='ArrowLeft'){a.currentTime=Math.max(0,a.currentTime-5);v.currentTime=a.currentTime}});sync();
